#!/bin/bash
apt-get update
apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils
apt-get install -y xrdp
adduser xrdp ssl-cert
systemctl restart xrdp
ufw allow 3389/tcp
echo xfce4-session >~/.xsession
service xrdp restart
